-- MIGRATION 004: CREATE COURSES
CREATE TABLE IF NOT EXISTS public.courses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id UUID REFERENCES public.categories(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  short_description TEXT,
  description TEXT,
  thumbnail_url TEXT,
  banner_url TEXT,
  instructor_name TEXT DEFAULT 'LexEdu Instructor',
  level course_level DEFAULT 'BEGINNER',
  estimated_duration INTEGER DEFAULT 0,
  enrollment_type enrollment_type DEFAULT 'OPEN',
  status course_status DEFAULT 'DRAFT',
  is_featured BOOLEAN DEFAULT false,
  show_curriculum_publicly BOOLEAN DEFAULT true,
  allow_resource_download BOOLEAN DEFAULT true,
  sort_order INTEGER DEFAULT 0,
  learning_outcomes JSONB DEFAULT '[]'::jsonb,
  target_audience JSONB DEFAULT '[]'::jsonb,
  requirements JSONB DEFAULT '[]'::jsonb,
  is_paid BOOLEAN DEFAULT false,
  price NUMERIC DEFAULT 0,
  sale_price NUMERIC,
  is_demo BOOLEAN DEFAULT false,
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);
